Controllers/CompraController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpticaSanfrancisco.Models;
using OpticaSanfrancisco.Data;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace OpticaSanfrancisco.Controllers
{
    public class CompraController : Controller
    {
        private readonly ILogger< CompraController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public  CompraController(ILogger< CompraController> logger,
            ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }

        public IActionResult AddItem(int? id)
        {
           // var producto = _context.Productos.Find(id);

           // var orderDetail = new OrdenDetail();
           // orderDetail.productoID = producto.ID;
           // orderDetail.Nombre = producto.nombre;
           // orderDetail.Precio = producto.precio;
           // orderDetail.Cantidad = 1;
           // var name = _userManager.GetUserName(User);
//orderDetail.Email = name;

           // _context.Add(orderDetail);
            //_context.SaveChanges();
            return RedirectToAction("Index", "Catalogo");
        }

        public IActionResult Carrito()
        {
            var listContactos=_context.OrdenDetails.ToList();
            return View(listContactos);
        }
        public IActionResult Proceso()
        {
            var listContactos=_context.OrdenDetails.ToList();
            return View(listContactos);
        }
    }
}

Views/Compra/Carrito.cshtml
@model IEnumerable<OpticaSanfrancisco.Models.OrdenDetail>
@{
    ViewData["Title"] = "Carrito de Compras";
}

<section id="catalogue" class="catalogue section-bg" style="text-align: center;">
      <div class="container">

        <div class="section-title">
          <h2 data-aos="fade-in">Carrito de Compras</h2>
          <p data-aos="fade-in">Los producto seleccionados apareceran aca</p>
        </div>


    <div class="row catalogue-container" data-aos="fade-up">

    <table class="table table-hover">
    <thead class="tables">
        <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Cantidad)
                </th>
        </tr>
    </thead>
	@foreach (var item in Model)
	{
        @if (item.Email == @User.Identity.Name)
        {
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            </tr>
        }
	}
    </tbody>    
</table>
           
            </div>
    </section>

      <div class="get-started" style="text-align: center;">
                
               <button id="btt">  <a  style="text-align: center;border-radius: 4px;" asp-area="" asp-controller="Compra" asp-action="Proceso">Confirmar</a></button>
      </div>
      <br>

Views/Compra/Proceso.cshtml
@model IEnumerable<OpticaSanfrancisco.Models.OrdenDetail>
@{
    ViewData["Title"] = "En Proceso";
}
<section id="catalogue" class="catalogue section-bg" style="text-align: center;">
<div class="container">
 
    <div class="container">

        <div class="section-title">
          <h2 data-aos="fade-in">Proceso de Pago</h2>
        </div>


    

    <table class="table table-hover">
    <thead class="tables">
        <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Cantidad)
                </th>
        </tr>
    </thead>
	@foreach (var item in Model)
	{
        @if (item.Email == @User.Identity.Name)
        {
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            </tr>
        }
	}
    </tbody>    
</table>
  <div class="row" style="text-align: center;" >
    <div class="col-md-1 order-md-1"></div>
    <div class="col-md-10 order-md-1">
      <h4 style="text-align: center;" class="mb-3 colorForm">Facturación</h4>
      <form class="needs-validation" novalidate="">
        <div class="row">
          <div class="col-md-6 mb-3 formM">
            <label for="firstName" class="colorForm">Primer Nombre</label>
            <input type="text" class="form-control" id="firstName"  placeholder="Ingresa tu nombre" value="" required="">
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3 formM">
            <label for="lastName" class="colorForm">Apellidos</label>
            <input type="text" class="form-control" id="lastName" placeholder="Ingresa tu apellido" value="" required="">
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3 formM">
          <label for="email" class="colorForm">Email</label>
          <input type="text" class="form-control" id="email" placeholder="Ingresa tu correo you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>
        

        <div class="mb-3 formM">
          <label for="address" class="colorForm">Dirección</label>
          <input type="text" class="form-control" id="address" placeholder="Ingresa tu dirección 1234 Main St" required="">
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3 formM">
          <label for="address2" class="colorForm">Dirección <span class="text-muted">(Opcional)</span></label>
          <input type="text" class="form-control" id="address2" placeholder="Ingresa tu dirección">
        </div>

        <div class="row">
          <div class="col-md-5 mb-3 formM">
            <label for="country" class="colorForm">Pais</label>
            <select class="custom-select d-block w-100" id="country" style="height: 45px;" required="">
              <option value="">Elegir...</option>
              <option>Perú</option>
            </select>
            <div class="invalid-feedback">
              Selecciona un pais valido
            </div>
          </div>
          <div class="col-md-4 mb-3 formM">
            <label for="state" class="colorForm">Departamento</label>
            <select class="custom-select d-block w-100" style="height: 45px;" id="state" required="">
              <option value="">Elegir...</option>
              <option>Arequipa</option>
            
            </select>
            <div class="invalid-feedback">
             Selecciona un departamento
            </div>
          </div>
          <div class="col-md-3 mb-3 formM">
            <label for="zip" class="colorForm">Zip</label>
            <input type="text" class="form-control" id="zip" style="height: 45px;" placeholder="Ingresa el Zip" required="">
            <div class="invalid-feedback">
             El Zip es requerido
            </div>
          </div>
        </div>
        <hr class="mb-4">

        <label class="mb-3 colorForm" >Payment</label>

        <div class="d-block my-3 formM">
          <div class="custom-control custom-radio">
            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" style="background-color: #213B52;" checked="" required="">
            <label class="custom-control-label colorForm" for="credit" >Tarjeta de Credito</label>
          </div>
          <div class="custom-control custom-radio formM">
            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" style="background: #213B52;" required="">
            <label class="custom-control-label colorForm" for="debit" >Tarjeta de Debito</label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3 formM">
            <label for="cc-name" class="colorForm">Nombre del Propietario de la Tarjeta</label>
            <input type="text" class="form-control" id="cc-name" placeholder="Ingresa el nombre del propietario de la tarjeta" required="">
            <div class="invalid-feedback">
              El nombre es requerido
            </div>
          </div>
          <div class="col-md-6 mb-3 formM">
            <label for="cc-number" class="colorForm">Numero de la Tarjeta de Credito</label>
            <input type="text" class="form-control" id="cc-number" placeholder="Ingresa el numero de la tarjeta" required="">
            <div class="invalid-feedback">
              El numero de la tarjeta de credito es requerida
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3 formM">
            <label for="cc-expiration" class="colorForm">Fecha de Expiración</label>
            <input type="text" class="form-control" id="cc-expiration" placeholder="Fecha de expiración es requerida" required="">
            <div class="invalid-feedback">
            Fecha de expiración es requerida
            </div>
          </div>
          <div class="col-md-6 mb-3 formM">
            <label for="cc-cvv" class="colorForm">CVV</label>
            <input type="text" class="form-control" id="cc-cvv" placeholder="El CVV es requerido" required="">
            <div class="invalid-feedback">
              El CVV es requerido
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <div class="button">
        <button style="border-radius: 4px;" type="submit" onclick="confirm('Compra aceptada. Gracias por su compra');  clicked();">Comprar Ahora</button>
        </div>
        </form>
    </div>
  </div>
  <div class="col-md-1 order-md-1"></div>
 </div> 
 </section>




 